"""empty message

Revision ID: 949c5f9dacdf
Revises: c3473a5300aa
Create Date: 2023-07-13 12:01:42.377530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949c5f9dacdf'
down_revision = 'c3473a5300aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lga',
    sa.Column('lga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lga_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('lga_id')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_user_id', sa.Integer(), nullable=False),
    sa.Column('order_product_id', sa.Integer(), nullable=False),
    sa.Column('order_state_id', sa.Integer(), nullable=False),
    sa.Column('order_lga_id', sa.Integer(), nullable=False),
    sa.Column('order_email', sa.String(length=120), nullable=True),
    sa.Column('order_refno', sa.String(length=120), nullable=True),
    sa.Column('order_delivery_address', sa.String(length=120), nullable=False),
    sa.Column('order_product_qty', sa.Integer(), nullable=False),
    sa.Column('order_unitprice', sa.Float(), nullable=False),
    sa.Column('order_amt', sa.Float(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['order_lga_id'], ['lga.lga_id'], ),
    sa.ForeignKeyConstraint(['order_product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['order_state_id'], ['state.state_id'], ),
    sa.ForeignKeyConstraint(['order_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('reviews',
    sa.Column('rev_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rev_user_id', sa.Integer(), nullable=False),
    sa.Column('rev_productid', sa.Integer(), nullable=False),
    sa.Column('rev_text', sa.String(length=255), nullable=False),
    sa.Column('rev_title', sa.String(length=255), nullable=False),
    sa.Column('rev_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rev_productid'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['rev_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('rev_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_user_id', sa.Integer(), nullable=False),
    sa.Column('payment_order_id', sa.Integer(), nullable=False),
    sa.Column('payment_amt', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['payment_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_category', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_desc', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['product_slug'])
        batch_op.drop_constraint('product_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['product_userid'], ['user_id'])
        batch_op.create_foreign_key(None, 'category', ['product_category'], ['cat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_ibfk_1', 'category', ['product_userid'], ['cat_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('product_desc')
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_slug')
        batch_op.drop_column('product_category')

    op.drop_table('payment')
    op.drop_table('reviews')
    op.drop_table('order')
    op.drop_table('state')
    op.drop_table('lga')
    # ### end Alembic commands ###
